### PR TITLE
PyLint + Unittests

### PR DESCRIPTION
**Pull request by lremus**
- Implemented PyLint check of main
- Improved FeatureExporter_test.py
- Implemented testing of FeatureExporter_test.py

Build successfully ! Check the logs of Travis :)
Small question: 
Why is there a setup.py? We are not building a Python package am I right ? 

Suggestion:
Make PyLint an external tool in PyCharm
Check the .pylintrc file to see what this young man can do :)

### CODE REVIEW

**Comment by lremus** [comment]
Apparently CoverAlls detects a decrease on coverage, can you investigate on this?
Thanks

**Comment by lremus** [comment]
Thanks. I skipped it because I did not have the data locally, and I was too lazy.

**Comment by lremus** [comment]
I am surprised that the test was successful before, as I expect Travis not to have the data accessible. I'll dig that !

**Comment by lremus** [comment]
Why is there a setup.py? We are not building a Python package am I right ?

**Comment by lremus** [comment]
This is what I have without skipping:
```
======================================================================
ERROR: test_output_to_file (FeatureExporter_test.TestExporter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/remus/repos/text-mining-challenge/tests/FeatureExporter_test.py", line 28, in test_output_to_file
    train_df = pd.read_csv("data/training_set_test.txt", sep=" ", header=None)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 764, in __init__
    self._make_engine(self.engine)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 985, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/parsers.py", line 1605, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
FileNotFoundError: File b'data/training_set_test.txt' does not exist

----------------------------------------------------------------------
Ran 2 tests in 0.005s

FAILED (errors=1)
```

This is due to:
```
train_df = pd.read_csv("data/training_set_test.txt", sep=" ", header=None)
node_information_df = pd.read_csv("data/node_information_test.csv", sep=",", header=None)
```

When using `../data/` instead of `data/`, it then fails with:
```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/Users/remus/repos/text-mining-challenge/tests/FeatureExporter_test.py", line 42, in test_output_to_file
    exporter.exportTo('training_set_test.txt', feature)
  File "/Users/remus/repos/text-mining-challenge/featureEngineering/FeatureExporter.py", line 118, in exportTo
    self.feature.to_csv(FeatureExporter.pathListBuilder(filename, feature, **kargs)[0])
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/core/frame.py", line 1403, in to_csv
    formatter.save()
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/formats/format.py", line 1577, in save
    compression=self.compression)
  File "/Users/remus/Envs/louisvenv/lib/python3.5/site-packages/pandas/io/common.py", line 385, in _get_handle
    f = open(path_or_buf, mode, errors='replace')
FileNotFoundError: [Errno 2] No such file or directory: 'featureEngineering/originalFeatures/output/training_set_test.txt'
```


I am surprised that this test did not fail on your side, or on Travis server.
I guess using auxiliary files for testing in this manner is not a good idea...

**Comment by Edouard360** [comment]
I agree with you and I am not quite sure what is the best practice in that case.

A question though. Does your error comes from your attempt to run the test through PyCharm ? I encountered the same issue, since PyCharm assign the path value with the folder path in which your file is. In our case, $PROJECT_PATH+"tests/". 

I saw you tried to sidestep that issue, but I don't think what you tried to add was good practice...

The reason why the test doesn't fail on Travis, is that the `coverage` command, is run from the root of the project. Even if they are found in folders, or folders of folders, the test files run with the root path.

What I still find strange with PyCharm is that the modules of the project can always be imported in any files regardless of its location in the directory architecture. And yet, the variable PATH is still set to the absolute path of your `*.py` file, which would force us to use workarounds such as the one you proposed.

I think with regards to the  [coveralls-python](https://github.com/coveralls-clients/coveralls-python) repo, that's an expected behavior. Another solution for the data might simply be to put it elsewhere than on github, and therefore refer to urls instead. This is how [keras](https://github.com/fchollet/keras/blob/master/tests/keras/datasets/test_datasets.py) proceeds.

**Comment by lremus** [comment]
Thanks for the detailed answer.
A few remarks:

1. > "Does your error comes from your attempt to run the test through PyCharm ?"

This error comes both from running in Terminal and in PyCharm. We must make sure to always run every executable outside of PyCharm, for the reason you outlined in your following remarks.

2. > "I saw you tried to sidestep that issue, but I don't think what you tried to add was good practice..."

Totally agreed.  
I think that the `unittest` package is mainly designed to test python packages, which is not what our project is about. With a python package, you can clearly and easily import any module with `from MyPackage.MyModule import Whatever`.  
This is why I used this (very ugly) workaround :)

3. > "What I still find strange with PyCharm is that the modules of the project can always be imported in any files regardless of its location in the directory architecture"

I am not sure of what you mean. You can indeed use the syntax: `from ..tools import BadAssClass` or `from .awesome import WubaLubaDubDub`, but you need some location indication with the use of `.` and `..`

**Pull request merged**
